apiVersion: v1
kind: Service
metadata:
  name: workprofile-service
  namespace: workprofile
spec:
  type: NodePort
  selector:
    app: workprofile
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30080

