services:
  nginx:
    image: nginx:1.27-alpine
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "8080:80"  # http://localhost:8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks: [frontend, backend]

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    image: workprofile:test
    environment:
      - DB_HOST=mysql
      - DB_USER=flaskapp
      - DB_PASS=flaskapp
      - DB_NAME=exampleDb
      - PYTHONUNBUFFERED=1       
    expose:
      - "5000"
    networks: [backend]
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:5000/health >/dev/null || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 60s         

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=exampleDb
      - MYSQL_USER=flaskapp
      - MYSQL_PASSWORD=flaskapp
      - MYSQL_ROOT_PASSWORD=changeme
    volumes:
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - mysql_data:/var/lib/mysql
    networks: [backend]
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 20s

networks:
  frontend: {}
  backend: {}

volumes:
  mysql_data: {}

