name: WorkProfile CI/CD Pipeline (Docker Hub)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  IMAGE_NAME: workprofile

jobs:
  ci-cd-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate image tag
      id: generate-tag
      run: |
        TAG="build-$(date +%Y%m%d)-${GITHUB_SHA::7}"
        echo "tag=${TAG}" >> $GITHUB_OUTPUT
        echo "Generated tag: ${TAG}"

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        TAG=${{ steps.generate-tag.outputs.tag }}
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${TAG} .
        docker tag ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${TAG} ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

    - name: Run container for testing
      run: |
        docker run -d -p 5000:5000 --name workprofile-test ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
        sleep 5

    - name: Test root endpoint
      run: curl --fail http://localhost:5000/

    - name: Test /health endpoint
      run: curl --fail http://localhost:5000/health

    - name: Push image to Docker Hub
      run: |
        TAG=${{ steps.generate-tag.outputs.tag }}
        docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${TAG}
        docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

